import matplotlib.pyplot as plt 
import pathlib
from typing import Union, Tuple
import numpy as np
import pandas as pd
import re

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if type(data_fname) == str:
            data_fname = pathlib.Path(data_fname)
        if not (data_fname.exists()):
            raise ValueError ("File don't exist")
        else:
            self.data_fname = data_fname

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data = pd.read_json(self.data_fname)
        return self.data

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        hist = plt.hist(self.data['age'], bins=np.arange(0,101,10), range=(0,100))
        plt.show()
        return hist[0], hist[1]

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """
        pattern = re.compile(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")
        mask = self.data['email'].apply(lambda x: True if pattern.match(x) else False)
        self.valid_data = self.data[mask]
        self.valid_data.index = np.arange(len(self.valid_data['email']))
        return self.valid_data

    def fill_na_with_mean(self) -> Union[pd.DataFrame, np.ndarray]:
        """
        Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student. Returns the corrected DataFrame,
        as well as the row indices of the students that their new grades
        were generated.
        """
        df_q = self.data.loc[:,['q1','q2','q3','q4','q5']]
        mean_rows = df_q.mean(axis=1)
        nan_rows = np.ndarray([])
        nan_rows_bool = df_q.isnull().any(axis = 'columns')
        nan_rows = np.ndarray([])
        for row in range(len(nan_rows_bool)):
            if nan_rows_bool[row] == True:
                nan_rows = np.append(nan_rows, row)
        if len(nan_rows)>1:
            nan_rows = nan_rows[1:]
        for i, col in enumerate(df_q):
            df_q.iloc[:, i] = df_q.iloc[:, i].fillna(mean_rows)
        self.data.loc[:,['q1','q2','q3','q4','q5']] = df_q
        return self.data, nan_rows

    def correlate_gender_age(self) -> pd.DataFrame:
        """
        Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.
        Returns a DataFrame with a MultiIndex containing the gender and whether
        the subject is above 40 years of age, and the average score in each of
        the five questions.
        """
        df = self.data.loc[:,['gender','age','q1','q2','q3','q4','q5']]
        df = df.groupby(['gender',df.age>=40]).mean().drop(['age'], axis =1)
        return df

if __name__ == '__main__':
    a = QuestionnaireAnalysis(pathlib.Path('data.json'))
    a.read_data()
    #a.show_age_distrib()
    #a.remove_rows_without_mail()
    #a.fill_na_with_mean()
    #a.correlate_gender_age()
